server:
  port: ${HOST_PORT:9000}
  error:
    include-message: always
root:
  url: postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:stockservice}?ApplicationName=${spring.application.name}
  username: postgres
  password: password
spring:
  application:
    name: @project.name@
  r2dbc:
    url: r2dbc:${root.url}
    username: ${root.username}
    password: ${root.password}
  flyway:
    url: jdbc:${root.url}
    user: ${root.username}
    password: ${root.password}
  task:
    execution:
      pool:
        core-size: 3
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
service:
  stock-quantity: 200
aspect:
  enabled: true
iexcloud.public.key: pk_f47e28b2208f493081cfec74294b35d3
